# Generated by Django 6.1 on 2026-09-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='extra_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
